### ISSUE TITLE
Incompatible with react-app-rewired v2

### ISSUE THREAD

**Issue by alex3683** [cdharris/react-app-rewire-hot-loader#14]
`react-app-rewire-hot-loader` is incompatible with version 2.x.x of `react-app-rewired`, since they removed all utility helper functions, including `injectBabelPlugin` (source: https://github.com/timarney/react-app-rewired/releases/tag/2.0).
Downgrading `react-app-rewired` isn't an option when working with the most recent version of `create-react-app`. But it seems as if the `react-app-rewired` team is aware of this issue: https://github.com/timarney/react-app-rewired/pull/346#issuecomment-452306649

**Comment by ghost** [comment]
Really need to update this package for latest version of react-app-rewired (2.x).

**Comment by cdharris** [comment]
I'm not working on a React project at the moment so would appreciate pull requests for this :)

**Comment by cdharris** [comment]
This should hopefully be fixed by @Olafaloofian 's PR #16 
New v2.0.0 published.

**Comment by cdharris** [comment]
v2.0.1 published as per #17 that should restore this functionality now.
