### ISSUE TITLE
Publish v1.0.1 to npm please

### ISSUE THREAD

**Issue by BerndWessels** [cdharris/react-app-rewire-hot-loader#6]
Hi,

awesome to see that you've already upgraded to hot-loader 4.

But I think you forgot to publish it to npm.

Could you please publish v1.0.1 with hot-loader 4 support.

**Comment by cdharris** [comment]
Hey Bernd, thanks for the polite tip

v1.0.1 should be published now cheers

**Comment by BerndWessels** [comment]
awesome, thanks
